a = input('Digite algo: ')
print('É alfabético e numérico?', a.isalnum())
print('É maiúsculo?', a.isupper())
print('É minúsculo?', a.islower())
print('É alfabético?', a.isalpha())
print('É um número?', a.isnumeric())
print('Só tem espaços?', a.isspace())
print('Só tem a primeira letra maiúscula?', a.istitle())
print('É um decimal?', a.isdecimal())